/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171223: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.31 seconds to train this model.
INFO:__main__:Model 1, model_id: fddbb35a-50e7-4537-ba91-65dee51722e5,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.33 seconds
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4294, in create_block_manager_from_blocks
    placement=slice(0, len(axes[0])))]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 2719, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 115, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 105, placement implies 86928

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_test_utils.py", line 291, in <module>
    search_regression_ml(5, 1, datetime.date(2017, 12, 24))
  File "train_test_utils.py", line 237, in search_regression_ml
    pipeline_param_grid=pipeline_param_grid
  File "train_test_utils.py", line 75, in train
    X = pipeline_1.fit_transform(X)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 301, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 234, in _fit
    Xt = transform.fit_transform(Xt, y, **fit_params_steps[name])
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 494, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "./../data_processing/imputation.py", line 100, in transform
    X = self.method_imputed(data_after_remove_weekend)
  File "./../data_processing/imputation.py", line 83, in method_imputed
    data_after_imputation = pd.DataFrame(np.array(data_copy), index=data.index, columns=data.columns)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 306, in __init__
    copy=copy)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 483, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4303, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4280, in construction_error
    passed, implied))
ValueError: Shape of passed values is (105, 1559), indices imply (86928, 1559)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.23 seconds to train this model.
INFO:__main__:Model 1, model_id: 45715f3b-4488-4dbf-8691-6a40d4acabb4,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.24 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1505, 639), y: (1505,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.333333333333
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.056512, total=  13.3s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.083399, total=  10.2s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.186615, total=   5.5s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [ 82 201 305 409 435 436 513 539 540 617] are constant.
  UserWarning)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.6s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 27.71 seconds to train this model.
INFO:__main__:Model 2, model_id: 2fbecc4d-95da-4363-ac3d-1be3b9002797,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 27.73 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1528, 639), y: (1528,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:3.06390256154
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.6s finished
INFO:__main__:It takes 29.96 seconds to train this model.
INFO:__main__:Model 3, model_id: f55ebe67-233e-4e86-8134-007eba6f6f21,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 29.98 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.86 seconds to train this model.
INFO:__main__:Model 4, model_id: e4345f43-b6df-4fd5-80a6-3130ff0b3035,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 20.87 seconds
INFO:__main__:We have run 5 models, using 98.82 seconds
Traceback (most recent call last):
  File "train_test_utils.py", line 291, in <module>
    search_regression_ml(5, 1, datetime.date(2017, 12, 24))
  File "train_test_utils.py", line 279, in search_regression_ml
    for index_i in range(results.index):
TypeError: 'RangeIndex' object cannot be interpreted as an integer
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.37 seconds to train this model.
INFO:__main__:Model 1, model_id: aa02c7b2-925d-499c-99b2-30866f7c8f04,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.39 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1505, 639), y: (1505,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.333333333333
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.4s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 27.22 seconds to train this model.
INFO:__main__:Model 2, model_id: 87d990b7-c263-4e62-b6a3-85236687bcf5,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 27.24 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1528, 639), y: (1528,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:3.06390256154
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.6s finished
INFO:__main__:It takes 29.56 seconds to train this model.
INFO:__main__:Model 3, model_id: 03eff47c-7941-4fd8-ae01-16068ab18826,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 29.58 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 21.27 seconds to train this model.
INFO:__main__:Model 4, model_id: c598ccd2-44a5-4180-b82b-596131375cf8,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 21.28 seconds
INFO:__main__:We have run 5 models, using 98.49 seconds
INFO:__main__:Saving aa02c7b2-925d-499c-99b2-30866f7c8f04 to disk...
Traceback (most recent call last):
  File "train_test_utils.py", line 291, in <module>
    search_regression_ml(5, 1, datetime.date(2017, 12, 24))
  File "train_test_utils.py", line 282, in search_regression_ml
    save_pipeline(save_model_dict[model_id_i], model_id_i)
  File "train_test_utils.py", line 125, in save_pipeline
    model_save_path = os.path.join("../results/models/", "model_" + model_id + ".pkl")
TypeError: must be str, not UUID
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.15 seconds to train this model.
INFO:__main__:Model 1, model_id: 034f048c-e0d7-44aa-bbf3-a9869dc549f1,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.16 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1505, 639), y: (1505,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.333333333333
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.5s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 27.30 seconds to train this model.
INFO:__main__:Model 2, model_id: 9131d269-e43d-4d92-8b98-c92fe58fc313,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 27.32 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1528, 639), y: (1528,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:3.06390256154
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.7s finished
INFO:__main__:It takes 29.59 seconds to train this model.
INFO:__main__:Model 3, model_id: fa4659b5-a7de-4d0b-bcaf-d83ac409d0cd,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 29.60 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.058482, total=   9.6s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.070834, total=   8.1s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [ 77 196 300 404 435 436 506 508 539 540 610 612] are constant.
  UserWarning)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 21.22 seconds to train this model.
INFO:__main__:Model 4, model_id: b1b3c47f-2a9a-405f-9b53-87538699c32f,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 21.23 seconds
INFO:__main__:We have run 5 models, using 98.31 seconds
INFO:__main__:Saving 034f048c-e0d7-44aa-bbf3-a9869dc549f1 to disk...
INFO:__main__:Model dumped into ../results/models/model_034f048c-e0d7-44aa-bbf3-a9869dc549f1.pkl.
INFO:__main__:Saving 9131d269-e43d-4d92-8b98-c92fe58fc313 to disk...
INFO:__main__:Model dumped into ../results/models/model_9131d269-e43d-4d92-8b98-c92fe58fc313.pkl.
INFO:__main__:Saving fa4659b5-a7de-4d0b-bcaf-d83ac409d0cd to disk...
INFO:__main__:Model dumped into ../results/models/model_fa4659b5-a7de-4d0b-bcaf-d83ac409d0cd.pkl.
INFO:__main__:Saving b1b3c47f-2a9a-405f-9b53-87538699c32f to disk...
INFO:__main__:Model dumped into ../results/models/model_b1b3c47f-2a9a-405f-9b53-87538699c32f.pkl.
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Index(['银行间质押式回购加权利率:7天'], dtype='object')
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   10.0s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.58 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 055418e1-c6b8-4a3e-8d6e-9505facdebf4,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 22.98 seconds
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.7s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in square
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:It takes 27.88 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: 62e99367-92a5-42e1-9a72-f2d7916be0d6,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 30.95 seconds
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:It takes 29.78 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: bb0ae734-6ab1-44dd-93ae-7ebd30aa9894,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 32.85 seconds
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   10.2s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 21.44 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 735d6892-0b44-4c9c-a909-533e44626f34,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 24.51 seconds
INFO:__main__:We have run 5 models, using 111.29 seconds
INFO:__main__:Saving 055418e1-c6b8-4a3e-8d6e-9505facdebf4 to disk...
INFO:__main__:Model dumped into ../results/models/model_055418e1-c6b8-4a3e-8d6e-9505facdebf4.pkl.
INFO:__main__:Saving 735d6892-0b44-4c9c-a909-533e44626f34 to disk...
INFO:__main__:Model dumped into ../results/models/model_735d6892-0b44-4c9c-a909-533e44626f34.pkl.
INFO:__main__:Saving 62e99367-92a5-42e1-9a72-f2d7916be0d6 to disk...
INFO:__main__:Model dumped into ../results/models/model_62e99367-92a5-42e1-9a72-f2d7916be0d6.pkl.
INFO:__main__:Saving bb0ae734-6ab1-44dd-93ae-7ebd30aa9894 to disk...
INFO:__main__:Model dumped into ../results/models/model_bb0ae734-6ab1-44dd-93ae-7ebd30aa9894.pkl.
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model 055418e1-c6b8-4a3e-8d6e-9505facdebf4 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model 735d6892-0b44-4c9c-a909-533e44626f34 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model 62e99367-92a5-42e1-9a72-f2d7916be0d6 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model bb0ae734-6ab1-44dd-93ae-7ebd30aa9894 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:Prediction finished!!!
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Index(['银行间质押式回购加权利率:7天'], dtype='object')
INFO:__main__:Index(['y'], dtype='object')
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 055418e1-c6b8-4a3e-8d6e-9505facdebf4, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 735d6892-0b44-4c9c-a909-533e44626f34, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in square
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 62e99367-92a5-42e1-9a72-f2d7916be0d6, model_name: random_forest, metric: 50.0
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: bb0ae734-6ab1-44dd-93ae-7ebd30aa9894, model_name: random_forest, metric: 50.0
INFO:__main__:Prediction finished!!!
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "pandas/_libs/tslib.pyx", line 2469, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:44294)
  File "pandas/_libs/src/datetime.pxd", line 132, in datetime._string_to_dts (pandas/_libs/tslib.c:97337)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/tslib.pyx", line 2491, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:44703)
  File "pandas/_libs/tslib.pyx", line 1955, in pandas._libs.tslib.parse_datetime_string (pandas/_libs/tslib.c:35351)
  File "/opt/anaconda3/lib/python3.6/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_test_utils.py", line 342, in <module>
    refit=True
  File "train_test_utils.py", line 144, in test
    X = pipeline_before_selector.transform(X)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 445, in _transform
    Xt = transform.transform(Xt)
  File "./../data_processing/imputation.py", line 92, in transform
    data_after_remove_weekend = self.remove_weekend(X)
  File "./../data_processing/imputation.py", line 26, in remove_weekend
    data.index = pd.to_datetime(data.index)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 514, in to_datetime
    result = _convert_listlike(arg, box, format, name=arg.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 435, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 2355, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:46617)
  File "pandas/_libs/tslib.pyx", line 2583, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:46321)
  File "pandas/_libs/tslib.pyx", line 2497, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:44803)
TypeError: invalid string coercion to datetime
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:-2]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3379, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [-2] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:data.shape[0]-2]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3379, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2183] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:data.shape[0]-2, :]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 856, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3379, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2183] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:data.shape[0]-2, :]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 856, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 1515, in slice_indexer
    return Index.slice_indexer(self, start, end, step, kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 1462, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.datetimes.DatetimeIndex'> with these indexers [2181] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (5, 639)
Traceback (most recent call last):
  File "train_test_utils.py", line 343, in <module>
    refit=True
  File "train_test_utils.py", line 170, in test
    X_copy = data_test[["y", "forward_y"]]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2056, in __getitem__
    return self._getitem_array(key)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2100, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['y'] not in index"
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 055418e1-c6b8-4a3e-8d6e-9505facdebf4, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 735d6892-0b44-4c9c-a909-533e44626f34, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in square
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 62e99367-92a5-42e1-9a72-f2d7916be0d6, model_name: random_forest, metric: 50.0
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: bb0ae734-6ab1-44dd-93ae-7ebd30aa9894, model_name: random_forest, metric: 50.0
INFO:__main__:Prediction finished!!!
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 381, in <module>
    model_results = pd.read_csv(results_path, encoding="utf-8")
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'./../results/model_history/regression_results_1.csv' does not exist
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171225: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   0.9s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.1s finished
INFO:__main__:It takes 196.29 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 34e1b05e-8fc2-4954-ac38-404898c3f593,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_20, eval_metric: 20.0using 399.20 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.132970, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.053780, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.065949, total=   1.1s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.3s finished
INFO:__main__:It takes 212.63 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: d53d460b-a211-466b-9375-f0a8cd7ae5b4,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_20, eval_metric: 28.000000000000004using 438.10 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.074409, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.262039, total=   0.6s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 213.39 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: 34ee0515-ae32-4e48-b6d8-788d613500f2,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_20, eval_metric: 24.0using 403.60 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   0.8s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 190.30 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 24ee7e21-da57-4516-8a96-676207aa3b07,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_20, eval_metric: 20.0using 382.46 seconds
INFO:__main__:We have run 5 models, using 1623.37 seconds
INFO:__main__:Saving d53d460b-a211-466b-9375-f0a8cd7ae5b4 to disk...
INFO:__main__:Model dumped into ../results/models/model_d53d460b-a211-466b-9375-f0a8cd7ae5b4.pkl.
INFO:__main__:Saving 34ee0515-ae32-4e48-b6d8-788d613500f2 to disk...
INFO:__main__:Model dumped into ../results/models/model_34ee0515-ae32-4e48-b6d8-788d613500f2.pkl.
INFO:__main__:Saving 34e1b05e-8fc2-4954-ac38-404898c3f593 to disk...
INFO:__main__:Model dumped into ../results/models/model_34e1b05e-8fc2-4954-ac38-404898c3f593.pkl.
Traceback (most recent call last):
  File "train_test_utils.py", line 376, in <module>
    validation_period_length=args.validation_period_length
  File "train_test_utils.py", line 328, in search_regression_ml
    json.dump(model_params_dict, fp)
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Pipeline' is not JSON serializable
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   1.2s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.4s finished
INFO:__main__:It takes 232.50 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 4ab8cd0c-8bcf-432d-b4b4-e5342f00d311,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_20, eval_metric: 20.0using 464.95 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.053780, total=   0.9s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.132970, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    2.9s finished
INFO:__main__:It takes 229.31 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: b200c54f-f5ae-4f80-a975-5e6bb57318ff,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_20, eval_metric: 28.000000000000004using 454.66 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.262039, total=   0.8s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.074409, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 234.62 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: 7a1a350d-eff4-4445-ae45-2418ba98cb92,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_20, eval_metric: 24.0using 478.92 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   1.1s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.2s finished
INFO:__main__:It takes 231.94 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 917c4c04-4655-4085-9cc6-078863d9d3e1,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_20, eval_metric: 20.0using 452.36 seconds
INFO:__main__:We have run 5 models, using 1850.89 seconds
INFO:__main__:Saving b200c54f-f5ae-4f80-a975-5e6bb57318ff to disk...
INFO:__main__:Model dumped into ../results/models/model_b200c54f-f5ae-4f80-a975-5e6bb57318ff.pkl.
INFO:__main__:Saving 7a1a350d-eff4-4445-ae45-2418ba98cb92 to disk...
INFO:__main__:Model dumped into ../results/models/model_7a1a350d-eff4-4445-ae45-2418ba98cb92.pkl.
INFO:__main__:Saving 4ab8cd0c-8bcf-432d-b4b4-e5342f00d311 to disk...
INFO:__main__:Model dumped into ../results/models/model_4ab8cd0c-8bcf-432d-b4b4-e5342f00d311.pkl.
Traceback (most recent call last):
  File "train_test_utils.py", line 379, in <module>
    data=data.copy(),
  File "train_test_utils.py", line 331, in search_regression_ml
    with open(model_params_json_path, 'w') as fp:
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImputationMethod' is not JSON serializable
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
Traceback (most recent call last):
  File "train_test_utils.py", line 383, in <module>
    validation_period_length=args.validation_period_length
  File "train_test_utils.py", line 235, in search_regression_ml
    model_params_dict = json.loads(model_params_json_path)
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   1.0s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   1.1s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.2s finished
INFO:__main__:It takes 237.23 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 4faea703-d959-4a86-b967-40f18b465b9d,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_20, eval_metric: 20.0using 465.62 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.065949, total=   1.0s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.2s finished
INFO:__main__:It takes 240.75 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: 27d34e6c-8f8c-4fdb-8bc8-c0a677c61869,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_20, eval_metric: 28.000000000000004using 466.20 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
