/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171223: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.31 seconds to train this model.
INFO:__main__:Model 1, model_id: fddbb35a-50e7-4537-ba91-65dee51722e5,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.33 seconds
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4294, in create_block_manager_from_blocks
    placement=slice(0, len(axes[0])))]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 2719, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 115, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 105, placement implies 86928

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_test_utils.py", line 291, in <module>
    search_regression_ml(5, 1, datetime.date(2017, 12, 24))
  File "train_test_utils.py", line 237, in search_regression_ml
    pipeline_param_grid=pipeline_param_grid
  File "train_test_utils.py", line 75, in train
    X = pipeline_1.fit_transform(X)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 301, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 234, in _fit
    Xt = transform.fit_transform(Xt, y, **fit_params_steps[name])
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 494, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "./../data_processing/imputation.py", line 100, in transform
    X = self.method_imputed(data_after_remove_weekend)
  File "./../data_processing/imputation.py", line 83, in method_imputed
    data_after_imputation = pd.DataFrame(np.array(data_copy), index=data.index, columns=data.columns)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 306, in __init__
    copy=copy)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 483, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4303, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4280, in construction_error
    passed, implied))
ValueError: Shape of passed values is (105, 1559), indices imply (86928, 1559)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.23 seconds to train this model.
INFO:__main__:Model 1, model_id: 45715f3b-4488-4dbf-8691-6a40d4acabb4,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.24 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1505, 639), y: (1505,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.333333333333
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.056512, total=  13.3s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.083399, total=  10.2s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.186615, total=   5.5s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [ 82 201 305 409 435 436 513 539 540 617] are constant.
  UserWarning)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.6s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 27.71 seconds to train this model.
INFO:__main__:Model 2, model_id: 2fbecc4d-95da-4363-ac3d-1be3b9002797,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 27.73 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1528, 639), y: (1528,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:3.06390256154
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.6s finished
INFO:__main__:It takes 29.96 seconds to train this model.
INFO:__main__:Model 3, model_id: f55ebe67-233e-4e86-8134-007eba6f6f21,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 29.98 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.86 seconds to train this model.
INFO:__main__:Model 4, model_id: e4345f43-b6df-4fd5-80a6-3130ff0b3035,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 20.87 seconds
INFO:__main__:We have run 5 models, using 98.82 seconds
Traceback (most recent call last):
  File "train_test_utils.py", line 291, in <module>
    search_regression_ml(5, 1, datetime.date(2017, 12, 24))
  File "train_test_utils.py", line 279, in search_regression_ml
    for index_i in range(results.index):
TypeError: 'RangeIndex' object cannot be interpreted as an integer
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.37 seconds to train this model.
INFO:__main__:Model 1, model_id: aa02c7b2-925d-499c-99b2-30866f7c8f04,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.39 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1505, 639), y: (1505,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.333333333333
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.4s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 27.22 seconds to train this model.
INFO:__main__:Model 2, model_id: 87d990b7-c263-4e62-b6a3-85236687bcf5,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 27.24 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1528, 639), y: (1528,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:3.06390256154
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.6s finished
INFO:__main__:It takes 29.56 seconds to train this model.
INFO:__main__:Model 3, model_id: 03eff47c-7941-4fd8-ae01-16068ab18826,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 29.58 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 21.27 seconds to train this model.
INFO:__main__:Model 4, model_id: c598ccd2-44a5-4180-b82b-596131375cf8,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 21.28 seconds
INFO:__main__:We have run 5 models, using 98.49 seconds
INFO:__main__:Saving aa02c7b2-925d-499c-99b2-30866f7c8f04 to disk...
Traceback (most recent call last):
  File "train_test_utils.py", line 291, in <module>
    search_regression_ml(5, 1, datetime.date(2017, 12, 24))
  File "train_test_utils.py", line 282, in search_regression_ml
    save_pipeline(save_model_dict[model_id_i], model_id_i)
  File "train_test_utils.py", line 125, in save_pipeline
    model_save_path = os.path.join("../results/models/", "model_" + model_id + ".pkl")
TypeError: must be str, not UUID
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.15 seconds to train this model.
INFO:__main__:Model 1, model_id: 034f048c-e0d7-44aa-bbf3-a9869dc549f1,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 20.16 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1505, 639), y: (1505,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.333333333333
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.5s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 27.30 seconds to train this model.
INFO:__main__:Model 2, model_id: 9131d269-e43d-4d92-8b98-c92fe58fc313,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 27.32 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1528, 639), y: (1528,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:3.06390256154
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.7s finished
INFO:__main__:It takes 29.59 seconds to train this model.
INFO:__main__:Model 3, model_id: fa4659b5-a7de-4d0b-bcaf-d83ac409d0cd,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 29.60 seconds
./../feature_engineering/feature_extract.py:111: RuntimeWarning: invalid value encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
./../feature_engineering/feature_extract.py:111: RuntimeWarning: divide by zero encountered in double_scalars
  rate_list.append(abs((data[j][i] - data[j-1][i]) / data[j-1][i]))
INFO:__main__:x_columns: 639, unique: 639
INFO:__main__:X_train: (1493, 639), y: (1493,)
INFO:__main__:(array([], dtype=int64), array([], dtype=int64))
INFO:__main__:0.0
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.058482, total=   9.6s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.070834, total=   8.1s
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [ 77 196 300 404 435 436 506 508 539 540 610 612] are constant.
  UserWarning)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.9s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 21.22 seconds to train this model.
INFO:__main__:Model 4, model_id: b1b3c47f-2a9a-405f-9b53-87538699c32f,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 21.23 seconds
INFO:__main__:We have run 5 models, using 98.31 seconds
INFO:__main__:Saving 034f048c-e0d7-44aa-bbf3-a9869dc549f1 to disk...
INFO:__main__:Model dumped into ../results/models/model_034f048c-e0d7-44aa-bbf3-a9869dc549f1.pkl.
INFO:__main__:Saving 9131d269-e43d-4d92-8b98-c92fe58fc313 to disk...
INFO:__main__:Model dumped into ../results/models/model_9131d269-e43d-4d92-8b98-c92fe58fc313.pkl.
INFO:__main__:Saving fa4659b5-a7de-4d0b-bcaf-d83ac409d0cd to disk...
INFO:__main__:Model dumped into ../results/models/model_fa4659b5-a7de-4d0b-bcaf-d83ac409d0cd.pkl.
INFO:__main__:Saving b1b3c47f-2a9a-405f-9b53-87538699c32f to disk...
INFO:__main__:Model dumped into ../results/models/model_b1b3c47f-2a9a-405f-9b53-87538699c32f.pkl.
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Index(['银行间质押式回购加权利率:7天'], dtype='object')
INFO:__main__:Index(['y'], dtype='object')
INFO:__main__:Tuning models, 20171224: 
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   10.0s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 20.58 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 055418e1-c6b8-4a3e-8d6e-9505facdebf4,model_name: random_forest, impute_method: directly, model_selector: all_selector, using 22.98 seconds
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   13.7s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in square
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:It takes 27.88 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: 62e99367-92a5-42e1-9a72-f2d7916be0d6,model_name: random_forest, impute_method: slinear, model_selector: all_selector, using 30.95 seconds
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   14.8s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:It takes 29.78 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: bb0ae734-6ab1-44dd-93ae-7ebd30aa9894,model_name: random_forest, impute_method: cubic, model_selector: all_selector, using 32.85 seconds
INFO:__main__:X_train: (1525, 639), y: (1525,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:   10.2s finished
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:It takes 21.44 seconds to train this model.
INFO:__main__:X_test: (24, 639)
train_test_utils.py:170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 735d6892-0b44-4c9c-a909-533e44626f34,model_name: random_forest, impute_method: zero, model_selector: all_selector, using 24.51 seconds
INFO:__main__:We have run 5 models, using 111.29 seconds
INFO:__main__:Saving 055418e1-c6b8-4a3e-8d6e-9505facdebf4 to disk...
INFO:__main__:Model dumped into ../results/models/model_055418e1-c6b8-4a3e-8d6e-9505facdebf4.pkl.
INFO:__main__:Saving 735d6892-0b44-4c9c-a909-533e44626f34 to disk...
INFO:__main__:Model dumped into ../results/models/model_735d6892-0b44-4c9c-a909-533e44626f34.pkl.
INFO:__main__:Saving 62e99367-92a5-42e1-9a72-f2d7916be0d6 to disk...
INFO:__main__:Model dumped into ../results/models/model_62e99367-92a5-42e1-9a72-f2d7916be0d6.pkl.
INFO:__main__:Saving bb0ae734-6ab1-44dd-93ae-7ebd30aa9894 to disk...
INFO:__main__:Model dumped into ../results/models/model_bb0ae734-6ab1-44dd-93ae-7ebd30aa9894.pkl.
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model 055418e1-c6b8-4a3e-8d6e-9505facdebf4 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model 735d6892-0b44-4c9c-a909-533e44626f34 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model 62e99367-92a5-42e1-9a72-f2d7916be0d6 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:X_train: (1555, 639), y_train: (1555,)
INFO:__main__:model bb0ae734-6ab1-44dd-93ae-7ebd30aa9894 does not exists
INFO:__main__:Input contains NaN, infinity or a value too large for dtype('float64').
INFO:__main__:Prediction finished!!!
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Index(['银行间质押式回购加权利率:7天'], dtype='object')
INFO:__main__:Index(['y'], dtype='object')
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 055418e1-c6b8-4a3e-8d6e-9505facdebf4, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 735d6892-0b44-4c9c-a909-533e44626f34, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in square
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 62e99367-92a5-42e1-9a72-f2d7916be0d6, model_name: random_forest, metric: 50.0
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (4, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: bb0ae734-6ab1-44dd-93ae-7ebd30aa9894, model_name: random_forest, metric: 50.0
INFO:__main__:Prediction finished!!!
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "pandas/_libs/tslib.pyx", line 2469, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:44294)
  File "pandas/_libs/src/datetime.pxd", line 132, in datetime._string_to_dts (pandas/_libs/tslib.c:97337)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/tslib.pyx", line 2491, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:44703)
  File "pandas/_libs/tslib.pyx", line 1955, in pandas._libs.tslib.parse_datetime_string (pandas/_libs/tslib.c:35351)
  File "/opt/anaconda3/lib/python3.6/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_test_utils.py", line 342, in <module>
    refit=True
  File "train_test_utils.py", line 144, in test
    X = pipeline_before_selector.transform(X)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 445, in _transform
    Xt = transform.transform(Xt)
  File "./../data_processing/imputation.py", line 92, in transform
    data_after_remove_weekend = self.remove_weekend(X)
  File "./../data_processing/imputation.py", line 26, in remove_weekend
    data.index = pd.to_datetime(data.index)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 514, in to_datetime
    result = _convert_listlike(arg, box, format, name=arg.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 435, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 2355, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:46617)
  File "pandas/_libs/tslib.pyx", line 2583, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:46321)
  File "pandas/_libs/tslib.pyx", line 2497, in pandas._libs.tslib.array_to_datetime (pandas/_libs/tslib.c:44803)
TypeError: invalid string coercion to datetime
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:-2]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3379, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [-2] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:data.shape[0]-2]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3379, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2183] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:data.shape[0]-2, :]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 856, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3379, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2183] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 321, in <module>
    data = data.loc[:data.shape[0]-2, :]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 856, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1506, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1356, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 1515, in slice_indexer
    return Index.slice_indexer(self, start, end, step, kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3301, in slice_indexer
    kind=kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3495, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3428, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 1462, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1469, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.datetimes.DatetimeIndex'> with these indexers [2181] of <class 'int'>
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (5, 639)
Traceback (most recent call last):
  File "train_test_utils.py", line 343, in <module>
    refit=True
  File "train_test_utils.py", line 170, in test
    X_copy = data_test[["y", "forward_y"]]
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2056, in __getitem__
    return self._getitem_array(key)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2100, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['y'] not in index"
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 055418e1-c6b8-4a3e-8d6e-9505facdebf4, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 735d6892-0b44-4c9c-a909-533e44626f34, model_name: random_forest, metric: 58.33333333333334
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in square
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: 62e99367-92a5-42e1-9a72-f2d7916be0d6, model_name: random_forest, metric: 50.0
train_test_utils.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_train.dropna(inplace=True)
INFO:__main__:X_train: (1545, 639), y_train: (1545,)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:310: RuntimeWarning: overflow encountered in square
  X = X ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:98: RuntimeWarning: overflow encountered in add
  square_of_sums_alldata = sum(sums_args) ** 2
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:99: RuntimeWarning: overflow encountered in square
  square_of_sums_args = [s ** 2 for s in sums_args]
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:100: RuntimeWarning: invalid value encountered in subtract
  sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
/opt/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:104: RuntimeWarning: invalid value encountered in subtract
  ssbn -= square_of_sums_alldata / float(n_samples)
INFO:__main__:X_test: (5, 639)
train_test_utils.py:171: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model: bb0ae734-6ab1-44dd-93ae-7ebd30aa9894, model_name: random_forest, metric: 50.0
INFO:__main__:Prediction finished!!!
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "train_test_utils.py", line 381, in <module>
    model_results = pd.read_csv(results_path, encoding="utf-8")
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'./../results/model_history/regression_results_1.csv' does not exist
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171225: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   0.9s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.1s finished
INFO:__main__:It takes 196.29 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 34e1b05e-8fc2-4954-ac38-404898c3f593,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_20, eval_metric: 20.0using 399.20 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.132970, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.053780, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.065949, total=   1.1s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.3s finished
INFO:__main__:It takes 212.63 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: d53d460b-a211-466b-9375-f0a8cd7ae5b4,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_20, eval_metric: 28.000000000000004using 438.10 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.074409, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.262039, total=   0.6s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 213.39 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: 34ee0515-ae32-4e48-b6d8-788d613500f2,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_20, eval_metric: 24.0using 403.60 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   0.8s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 190.30 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 24ee7e21-da57-4516-8a96-676207aa3b07,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_20, eval_metric: 20.0using 382.46 seconds
INFO:__main__:We have run 5 models, using 1623.37 seconds
INFO:__main__:Saving d53d460b-a211-466b-9375-f0a8cd7ae5b4 to disk...
INFO:__main__:Model dumped into ../results/models/model_d53d460b-a211-466b-9375-f0a8cd7ae5b4.pkl.
INFO:__main__:Saving 34ee0515-ae32-4e48-b6d8-788d613500f2 to disk...
INFO:__main__:Model dumped into ../results/models/model_34ee0515-ae32-4e48-b6d8-788d613500f2.pkl.
INFO:__main__:Saving 34e1b05e-8fc2-4954-ac38-404898c3f593 to disk...
INFO:__main__:Model dumped into ../results/models/model_34e1b05e-8fc2-4954-ac38-404898c3f593.pkl.
Traceback (most recent call last):
  File "train_test_utils.py", line 376, in <module>
    validation_period_length=args.validation_period_length
  File "train_test_utils.py", line 328, in search_regression_ml
    json.dump(model_params_dict, fp)
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Pipeline' is not JSON serializable
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   1.2s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.4s finished
INFO:__main__:It takes 232.50 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 4ab8cd0c-8bcf-432d-b4b4-e5342f00d311,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_20, eval_metric: 20.0using 464.95 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.053780, total=   0.9s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.132970, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    2.9s finished
INFO:__main__:It takes 229.31 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: b200c54f-f5ae-4f80-a975-5e6bb57318ff,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_20, eval_metric: 28.000000000000004using 454.66 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.262039, total=   0.8s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.074409, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 234.62 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: 7a1a350d-eff4-4445-ae45-2418ba98cb92,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_20, eval_metric: 24.0using 478.92 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   1.1s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.2s finished
INFO:__main__:It takes 231.94 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 917c4c04-4655-4085-9cc6-078863d9d3e1,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_20, eval_metric: 20.0using 452.36 seconds
INFO:__main__:We have run 5 models, using 1850.89 seconds
INFO:__main__:Saving b200c54f-f5ae-4f80-a975-5e6bb57318ff to disk...
INFO:__main__:Model dumped into ../results/models/model_b200c54f-f5ae-4f80-a975-5e6bb57318ff.pkl.
INFO:__main__:Saving 7a1a350d-eff4-4445-ae45-2418ba98cb92 to disk...
INFO:__main__:Model dumped into ../results/models/model_7a1a350d-eff4-4445-ae45-2418ba98cb92.pkl.
INFO:__main__:Saving 4ab8cd0c-8bcf-432d-b4b4-e5342f00d311 to disk...
INFO:__main__:Model dumped into ../results/models/model_4ab8cd0c-8bcf-432d-b4b4-e5342f00d311.pkl.
Traceback (most recent call last):
  File "train_test_utils.py", line 379, in <module>
    data=data.copy(),
  File "train_test_utils.py", line 331, in search_regression_ml
    with open(model_params_json_path, 'w') as fp:
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImputationMethod' is not JSON serializable
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
Traceback (most recent call last):
  File "train_test_utils.py", line 383, in <module>
    validation_period_length=args.validation_period_length
  File "train_test_utils.py", line 235, in search_regression_ml
    model_params_dict = json.loads(model_params_json_path)
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   1.0s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   1.1s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   1.1s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.2s finished
INFO:__main__:It takes 237.23 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 4faea703-d959-4a86-b967-40f18b465b9d,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_20, eval_metric: 20.0using 465.62 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.065949, total=   1.0s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.2s finished
INFO:__main__:It takes 240.75 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: 27d34e6c-8f8c-4fdb-8bc8-c0a677c61869,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_20, eval_metric: 28.000000000000004using 466.20 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.262039, total=   0.8s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.200399, total=   0.8s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.074409, total=   0.8s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 229.85 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: 00671e15-8a8e-4016-a633-5f99405a9946,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_20, eval_metric: 24.0using 455.17 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 21), y: (1530,)
Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.199320, total=   0.7s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.183423, total=   0.6s
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV]  model__n_estimators=100, reducer__n_components=10, score=-0.085791, total=   0.7s
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.9s finished
INFO:__main__:It takes 225.78 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 21)
train_test_utils.py:173: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: fd4067a5-1bc0-4f04-85ef-1328a3ea0177,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_20, eval_metric: 20.0using 445.69 seconds
INFO:__main__:We have run 5 models, using 1832.68 seconds
INFO:__main__:Saving 27d34e6c-8f8c-4fdb-8bc8-c0a677c61869 to disk...
INFO:__main__:Model dumped into ../results/models/model_27d34e6c-8f8c-4fdb-8bc8-c0a677c61869.pkl.
INFO:__main__:Saving 00671e15-8a8e-4016-a633-5f99405a9946 to disk...
INFO:__main__:Model dumped into ../results/models/model_00671e15-8a8e-4016-a633-5f99405a9946.pkl.
INFO:__main__:Saving 4faea703-d959-4a86-b967-40f18b465b9d to disk...
INFO:__main__:Model dumped into ../results/models/model_4faea703-d959-4a86-b967-40f18b465b9d.pkl.
Traceback (most recent call last):
  File "train_test_utils.py", line 383, in <module>
    raw_data_url=os.path.join("./../data/data_live/", args.data_path)
  File "train_test_utils.py", line 332, in search_regression_ml
    
NameError: name 'model_params_dict' is not defined
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=1000, reducer__n_components=10 ..............
[CV] model__n_estimators=1000, reducer__n_components=10 ..............
[CV] model__n_estimators=500, reducer__n_components=10 ...............
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV] model__n_estimators=500, reducer__n_components=10 ...............
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV] model__n_estimators=1000, reducer__n_components=10 ..............
[CV] model__n_estimators=100, reducer__n_components=10 ...............
[CV] model__n_estimators=500, reducer__n_components=10 ...............
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 344, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 227, in _fit_and_score
    estimator.set_params(**parameters)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 180, in set_params
    self._set_params('steps', **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 69, in _set_params
    super(_BasePipeline, self).set_params(**params)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 282, in set_params
    (name, self))
ValueError: Invalid parameter reducer for estimator Pipeline(steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))), ('model', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=-1, oob_score=False, random_state=1234,
           verbose=0, warm_start=False))]). Check the list of available parameters with `estimator.get_params().keys()`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 353, in __call__
    raise TransportableException(text, e_type)
sklearn.externals.joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
ValueError                                         Tue Dec 26 04:59:26 2017
PID: 41174                          Python 3.6.1: /opt/anaconda3/bin/python
...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self=<sklearn.externals.joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _fit_and_score>, (Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), make_scorer(mean_squared_error, greater_is_better=False), array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), 3, {'model__n_estimators': 100, 'reducer__n_components': 10}), {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _fit_and_score>
        args = (Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), make_scorer(mean_squared_error, greater_is_better=False), array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), 3, {'model__n_estimators': 100, 'reducer__n_components': 10})
        kwargs = {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), X=array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), y=array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), scorer=make_scorer(mean_squared_error, greater_is_better=False), train=array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), test=array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), verbose=3, parameters={'model__n_estimators': 100, 'reducer__n_components': 10}, fit_params={}, return_train_score=True, return_parameters=True, return_n_test_samples=True, return_times=True, error_score='raise')
    222     fit_params = fit_params if fit_params is not None else {}
    223     fit_params = dict([(k, _index_param_value(X, v, train))
    224                       for k, v in fit_params.items()])
    225 
    226     if parameters is not None:
--> 227         estimator.set_params(**parameters)
        estimator.set_params = <bound method Pipeline.set_params of Pipeline(st...1234,
           verbose=0, warm_start=False))])>
        parameters = {'model__n_estimators': 100, 'reducer__n_components': 10}
    228 
    229     start_time = time.time()
    230 
    231     X_train, y_train = _safe_split(estimator, X, y, train)

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), **kwargs={'model__n_estimators': 100, 'reducer__n_components': 10})
    175 
    176         Returns
    177         -------
    178         self
    179         """
--> 180         self._set_params('steps', **kwargs)
        self._set_params = <bound method _BasePipeline._set_params of Pipel...1234,
           verbose=0, warm_start=False))])>
        kwargs = {'model__n_estimators': 100, 'reducer__n_components': 10}
    181         return self
    182 
    183     def _validate_steps(self):
    184         names, estimators = zip(*self.steps)

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), steps_attr='steps', **params={'model__n_estimators': 100, 'reducer__n_components': 10})
     64         step_names, _ = zip(*getattr(self, steps_attr))
     65         for name in list(six.iterkeys(params)):
     66             if '__' not in name and name in step_names:
     67                 self._replace_step(steps_attr, name, params.pop(name))
     68         # 3. Step parameters and other initilisation arguments
---> 69         super(_BasePipeline, self).set_params(**params)
        self.set_params = <bound method Pipeline.set_params of Pipeline(st...1234,
           verbose=0, warm_start=False))])>
        params = {'model__n_estimators': 100, 'reducer__n_components': 10}
     70         return self
     71 
     72     def _validate_names(self, names):
     73         if len(set(names)) != len(names):

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py in set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), **params={'model__n_estimators': 100, 'reducer__n_components': 10})
    277                 name, sub_name = split
    278                 if name not in valid_params:
    279                     raise ValueError('Invalid parameter %s for estimator %s. '
    280                                      'Check the list of available parameters '
    281                                      'with `estimator.get_params().keys()`.' %
--> 282                                      (name, self))
        name = 'reducer'
        self = Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))])
    283                 sub_object = valid_params[name]
    284                 sub_object.set_params(**{sub_name: value})
    285             else:
    286                 # simple objects case

ValueError: Invalid parameter reducer for estimator Pipeline(steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))), ('model', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=-1, oob_score=False, random_state=1234,
           verbose=0, warm_start=False))]). Check the list of available parameters with `estimator.get_params().keys()`.
___________________________________________________________________________
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 682, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/anaconda3/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
sklearn.externals.joblib.my_exceptions.TransportableException: TransportableException
___________________________________________________________________________
ValueError                                         Tue Dec 26 04:59:26 2017
PID: 41174                          Python 3.6.1: /opt/anaconda3/bin/python
...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self=<sklearn.externals.joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _fit_and_score>, (Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), make_scorer(mean_squared_error, greater_is_better=False), array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), 3, {'model__n_estimators': 100, 'reducer__n_components': 10}), {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _fit_and_score>
        args = (Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), make_scorer(mean_squared_error, greater_is_better=False), array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), 3, {'model__n_estimators': 100, 'reducer__n_components': 10})
        kwargs = {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), X=array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), y=array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), scorer=make_scorer(mean_squared_error, greater_is_better=False), train=array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), test=array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), verbose=3, parameters={'model__n_estimators': 100, 'reducer__n_components': 10}, fit_params={}, return_train_score=True, return_parameters=True, return_n_test_samples=True, return_times=True, error_score='raise')
    222     fit_params = fit_params if fit_params is not None else {}
    223     fit_params = dict([(k, _index_param_value(X, v, train))
    224                       for k, v in fit_params.items()])
    225 
    226     if parameters is not None:
--> 227         estimator.set_params(**parameters)
        estimator.set_params = <bound method Pipeline.set_params of Pipeline(st...1234,
           verbose=0, warm_start=False))])>
        parameters = {'model__n_estimators': 100, 'reducer__n_components': 10}
    228 
    229     start_time = time.time()
    230 
    231     X_train, y_train = _safe_split(estimator, X, y, train)

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), **kwargs={'model__n_estimators': 100, 'reducer__n_components': 10})
    175 
    176         Returns
    177         -------
    178         self
    179         """
--> 180         self._set_params('steps', **kwargs)
        self._set_params = <bound method _BasePipeline._set_params of Pipel...1234,
           verbose=0, warm_start=False))])>
        kwargs = {'model__n_estimators': 100, 'reducer__n_components': 10}
    181         return self
    182 
    183     def _validate_steps(self):
    184         names, estimators = zip(*self.steps)

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), steps_attr='steps', **params={'model__n_estimators': 100, 'reducer__n_components': 10})
     64         step_names, _ = zip(*getattr(self, steps_attr))
     65         for name in list(six.iterkeys(params)):
     66             if '__' not in name and name in step_names:
     67                 self._replace_step(steps_attr, name, params.pop(name))
     68         # 3. Step parameters and other initilisation arguments
---> 69         super(_BasePipeline, self).set_params(**params)
        self.set_params = <bound method Pipeline.set_params of Pipeline(st...1234,
           verbose=0, warm_start=False))])>
        params = {'model__n_estimators': 100, 'reducer__n_components': 10}
     70         return self
     71 
     72     def _validate_names(self, names):
     73         if len(set(names)) != len(names):

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py in set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), **params={'model__n_estimators': 100, 'reducer__n_components': 10})
    277                 name, sub_name = split
    278                 if name not in valid_params:
    279                     raise ValueError('Invalid parameter %s for estimator %s. '
    280                                      'Check the list of available parameters '
    281                                      'with `estimator.get_params().keys()`.' %
--> 282                                      (name, self))
        name = 'reducer'
        self = Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))])
    283                 sub_object = valid_params[name]
    284                 sub_object.set_params(**{sub_name: value})
    285             else:
    286                 # simple objects case

ValueError: Invalid parameter reducer for estimator Pipeline(steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))), ('model', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=-1, oob_score=False, random_state=1234,
           verbose=0, warm_start=False))]). Check the list of available parameters with `estimator.get_params().keys()`.
___________________________________________________________________________

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_test_utils.py", line 404, in <module>
    validation_period_length=args.validation_period_length
  File "train_test_utils.py", line 280, in search_regression_ml
    pipeline_param_grid=pipeline_param_grid
  File "train_test_utils.py", line 133, in train
    pipeline_2.fit(X_train, y_train)
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 564, in _fit
    for parameters in parameter_iterable
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 768, in __call__
    self.retrieve()
  File "/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 719, in retrieve
    raise exception
sklearn.externals.joblib.my_exceptions.JoblibValueError: JoblibValueError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/home/zhaoyi/code/repurchasing_in_production/train_test/train_test_utils.py in <module>()
    399         search_regression_ml(
    400             data=data.copy(),
    401             save_k_best=args.save_k_best,
    402             look_ahead_day=args.look_forward_days,
    403             split_date=datetime.datetime.strptime(args.split_date, "%Y%m%d").date(),
--> 404             validation_period_length=args.validation_period_length
    405         )
    406 
    407     # set the model results path
    408     results_path = os.path.join("./../results/model_history/", "regression_results_" + str(args.look_forward_days) + ".csv")

...........................................................................
/home/zhaoyi/code/repurchasing_in_production/train_test/train_test_utils.py in search_regression_ml(data=                 x1          x2         x3      ...NaN      NaN  3.0297  

[2183 rows x 105 columns], save_k_best=2, look_ahead_day=1, split_date=datetime.date(2017, 12, 18), validation_period_length=30)
    275                         reducer=PCA(n_components=10),  # temporarily not in use
    276                         model=model_dict[model_name],
    277                         X=data.copy(),
    278                         split_date=split_date - datetime.timedelta(days=validation_period_length),
    279                         pipeline_mode=model_pipeline_mode_dict[model_name],
--> 280                         pipeline_param_grid=pipeline_param_grid
        pipeline_param_grid = {'model__n_estimators': [100, 500, 1000], 'reducer__n_components': [10]}
    281                     )
    282                     model_id = str(uuid.uuid4())
    283                     y_test_predict = test(
    284                         data.copy(),

...........................................................................
/home/zhaoyi/code/repurchasing_in_production/train_test/train_test_utils.py in train(imputer=ImputationMethod(method='directly'), engineer=FeatureExtract(changerate=True, diff=True, ind=[...0, log=True,
        look_forward_days=1, ma=[5]), selector=HardThresholdSelector(alpha=0.05, date_column='d...
           select_top_k=True, target_column='y'), scaler=MinMaxScaler(copy=True, feature_range=(0, 1)), reducer=PCA(copy=True, iterated_power='auto', n_componen...None,
  svd_solver='auto', tol=0.0, whiten=False), model=RandomForestRegressor(bootstrap=True, criterion=...  random_state=1234, verbose=0, warm_start=False), X=               x59  x59_ind_2  x59_ma_5     x89 ...07  3.2785     3.3609  

[1530 rows x 12 columns], split_date=datetime.date(2017, 11, 18), pipeline_mode='grid', pipeline_param_grid={'model__n_estimators': [100, 500, 1000], 'reducer__n_components': [10]})
    128         search_pipeline=pipeline_2,
    129         pipeline_mode=pipeline_mode,
    130         param_grid=pipeline_param_grid
    131     )
    132 
--> 133     pipeline_2.fit(X_train, y_train)
        pipeline_2.fit = <bound method GridSearchCV.fit of GridSearchCV(c...    scoring='neg_mean_squared_error', verbose=3)>
        X_train = array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]])
        y_train = array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609])
    134     logger.info("It takes {:.2f} seconds to train this model.".format(time.time() - time_init))
    135     if pipeline_mode != "single":
    136         pipeline_2 = pipeline_2.best_estimator_
    137 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py in fit(self=GridSearchCV(cv=TimeSeriesSplit(n_splits=3), err...     scoring='neg_mean_squared_error', verbose=3), X=array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), y=array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), groups=None)
    940 
    941         groups : array-like, with shape (n_samples,), optional
    942             Group labels for the samples used while splitting the dataset into
    943             train/test set.
    944         """
--> 945         return self._fit(X, y, groups, ParameterGrid(self.param_grid))
        self._fit = <bound method BaseSearchCV._fit of GridSearchCV(...    scoring='neg_mean_squared_error', verbose=3)>
        X = array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]])
        y = array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609])
        groups = None
        self.param_grid = {'model__n_estimators': [100, 500, 1000], 'reducer__n_components': [10]}
    946 
    947 
    948 class RandomizedSearchCV(BaseSearchCV):
    949     """Randomized search on hyper parameters.

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py in _fit(self=GridSearchCV(cv=TimeSeriesSplit(n_splits=3), err...     scoring='neg_mean_squared_error', verbose=3), X=array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), y=array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), groups=None, parameter_iterable=<sklearn.model_selection._search.ParameterGrid object>)
    559                                   fit_params=self.fit_params,
    560                                   return_train_score=self.return_train_score,
    561                                   return_n_test_samples=True,
    562                                   return_times=True, return_parameters=True,
    563                                   error_score=self.error_score)
--> 564           for parameters in parameter_iterable
        parameters = undefined
        parameter_iterable = <sklearn.model_selection._search.ParameterGrid object>
    565           for train, test in cv_iter)
    566 
    567         # if one choose to see train score, "out" will contain train score info
    568         if self.return_train_score:

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self=Parallel(n_jobs=-1), iterable=<generator object BaseSearchCV._fit.<locals>.<genexpr>>)
    763             if pre_dispatch == "all" or n_jobs == 1:
    764                 # The iterable was consumed all at once by the above for loop.
    765                 # No need to wait for async callbacks to trigger to
    766                 # consumption.
    767                 self._iterating = False
--> 768             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-1)>
    769             # Make sure that we get a last message telling us we are done
    770             elapsed_time = time.time() - self._start_time
    771             self._print('Done %3i out of %3i | elapsed: %s finished',
    772                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
ValueError                                         Tue Dec 26 04:59:26 2017
PID: 41174                          Python 3.6.1: /opt/anaconda3/bin/python
...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self=<sklearn.externals.joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        self.items = [(<function _fit_and_score>, (Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), make_scorer(mean_squared_error, greater_is_better=False), array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), 3, {'model__n_estimators': 100, 'reducer__n_components': 10}), {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0=<list_iterator object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function _fit_and_score>
        args = (Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), make_scorer(mean_squared_error, greater_is_better=False), array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), 3, {'model__n_estimators': 100, 'reducer__n_components': 10})
        kwargs = {'error_score': 'raise', 'fit_params': {}, 'return_n_test_samples': True, 'return_parameters': True, 'return_times': True, 'return_train_score': True}
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), X=array([[  4.519     ,  20.421361  ,   4.20256   ...7.75956736,
          4.4407    ,   3.2785    ]]), y=array([ 4.0835,  3.9949,  4.1816, ...,  3.4924,  3.2785,  3.3609]), scorer=make_scorer(mean_squared_error, greater_is_better=False), train=array([  0,   1,   2,   3,   4,   5,   6,   7,  ..., 376,
       377, 378, 379, 380, 381, 382, 383]), test=array([384, 385, 386, 387, 388, 389, 390, 391, 3..., 758, 759, 760,
       761, 762, 763, 764, 765]), verbose=3, parameters={'model__n_estimators': 100, 'reducer__n_components': 10}, fit_params={}, return_train_score=True, return_parameters=True, return_n_test_samples=True, return_times=True, error_score='raise')
    222     fit_params = fit_params if fit_params is not None else {}
    223     fit_params = dict([(k, _index_param_value(X, v, train))
    224                       for k, v in fit_params.items()])
    225 
    226     if parameters is not None:
--> 227         estimator.set_params(**parameters)
        estimator.set_params = <bound method Pipeline.set_params of Pipeline(st...1234,
           verbose=0, warm_start=False))])>
        parameters = {'model__n_estimators': 100, 'reducer__n_components': 10}
    228 
    229     start_time = time.time()
    230 
    231     X_train, y_train = _safe_split(estimator, X, y, train)

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), **kwargs={'model__n_estimators': 100, 'reducer__n_components': 10})
    175 
    176         Returns
    177         -------
    178         self
    179         """
--> 180         self._set_params('steps', **kwargs)
        self._set_params = <bound method _BasePipeline._set_params of Pipel...1234,
           verbose=0, warm_start=False))])>
        kwargs = {'model__n_estimators': 100, 'reducer__n_components': 10}
    181         return self
    182 
    183     def _validate_steps(self):
    184         names, estimators = zip(*self.steps)

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), steps_attr='steps', **params={'model__n_estimators': 100, 'reducer__n_components': 10})
     64         step_names, _ = zip(*getattr(self, steps_attr))
     65         for name in list(six.iterkeys(params)):
     66             if '__' not in name and name in step_names:
     67                 self._replace_step(steps_attr, name, params.pop(name))
     68         # 3. Step parameters and other initilisation arguments
---> 69         super(_BasePipeline, self).set_params(**params)
        self.set_params = <bound method Pipeline.set_params of Pipeline(st...1234,
           verbose=0, warm_start=False))])>
        params = {'model__n_estimators': 100, 'reducer__n_components': 10}
     70         return self
     71 
     72     def _validate_names(self, names):
     73         if len(set(names)) != len(names):

...........................................................................
/opt/anaconda3/lib/python3.6/site-packages/sklearn/base.py in set_params(self=Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))]), **params={'model__n_estimators': 100, 'reducer__n_components': 10})
    277                 name, sub_name = split
    278                 if name not in valid_params:
    279                     raise ValueError('Invalid parameter %s for estimator %s. '
    280                                      'Check the list of available parameters '
    281                                      'with `estimator.get_params().keys()`.' %
--> 282                                      (name, self))
        name = 'reducer'
        self = Pipeline(steps=[('scaler', MinMaxScaler(copy=Tru...=1234,
           verbose=0, warm_start=False))])
    283                 sub_object = valid_params[name]
    284                 sub_object.set_params(**{sub_name: value})
    285             else:
    286                 # simple objects case

ValueError: Invalid parameter reducer for estimator Pipeline(steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))), ('model', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=-1, oob_score=False, random_state=1234,
           verbose=0, warm_start=False))]). Check the list of available parameters with `estimator.get_params().keys()`.
___________________________________________________________________________
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 1
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.129227, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.042354, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.064369, total=   0.6s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.8s remaining:    2.9s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.4s remaining:    1.2s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.3s finished
INFO:__main__:It takes 228.26 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: 43277782-ab16-4d66-830a-aa394e6273f4,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_10, eval_metric: 48.0using 449.82 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.032469, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.062438, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.154918, total=   0.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.153874, total=   1.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.032096, total=   1.5s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.062429, total=   1.9s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.154605, total=   2.7s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.062217, total=   3.4s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.032402, total=   3.1s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.8s remaining:    2.8s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.2s remaining:    1.1s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.0s finished
INFO:__main__:It takes 229.52 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: 02a8bbee-19f9-4280-b6e9-f5e6c8ad1a56,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_10, eval_metric: 48.0using 458.28 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.129227, total=   0.4s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.042354, total=   0.5s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.064369, total=   0.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.042454, total=   1.9s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.063432, total=   2.1s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.126654, total=   1.6s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.042783, total=   3.4s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.127402, total=   3.1s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.7s remaining:    2.4s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.4s remaining:    1.2s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.2s finished
INFO:__main__:It takes 236.50 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: c7c58713-7888-4ebd-af22-bfcb7a616dfe,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_10, eval_metric: 48.0using 466.12 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.129227, total=   0.5s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.064369, total=   0.7s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.042354, total=   0.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.126654, total=   1.4s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.042454, total=   1.7s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.063432, total=   2.2s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.127402, total=   2.6s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.042783, total=   2.9s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.063722, total=   3.7s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.8s remaining:    2.7s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.5s remaining:    1.2s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.3s finished
INFO:__main__:It takes 233.17 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: e73765f8-6471-4663-a972-f6394bb52ffe,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_10, eval_metric: 48.0using 458.40 seconds
INFO:__main__:We have run 5 models, using 1832.62 seconds
INFO:__main__:Saving 43277782-ab16-4d66-830a-aa394e6273f4 to disk...
INFO:__main__:Model dumped into ../results/models/model_43277782-ab16-4d66-830a-aa394e6273f4.pkl.
INFO:__main__:Saving 02a8bbee-19f9-4280-b6e9-f5e6c8ad1a56 to disk...
INFO:__main__:Model dumped into ../results/models/model_02a8bbee-19f9-4280-b6e9-f5e6c8ad1a56.pkl.
INFO:__main__:Saving c7c58713-7888-4ebd-af22-bfcb7a616dfe to disk...
INFO:__main__:Model dumped into ../results/models/model_c7c58713-7888-4ebd-af22-bfcb7a616dfe.pkl.
INFO:__main__:By filtering the best eval_metric, we select the only model 43277782-ab16-4d66-830a-aa394e6273f4, with eval_metric: 48.0
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
INFO:__main__:X_test: (5, 11)
INFO:__main__:Model: 43277782-ab16-4d66-830a-aa394e6273f4, model_name: random_forest, metric: 48.0
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
INFO:__main__:X_test: (5, 11)
INFO:__main__:Model: 02a8bbee-19f9-4280-b6e9-f5e6c8ad1a56, model_name: random_forest, metric: 48.0
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
INFO:__main__:X_test: (5, 11)
INFO:__main__:Model: c7c58713-7888-4ebd-af22-bfcb7a616dfe, model_name: random_forest, metric: 48.0
INFO:__main__:Prediction finished!!!
done
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
INFO:__main__:Setting is_training to be true, we run grid search on look_forward_days to be 2
INFO:__main__:Tuning models, 20171226: 
INFO:__main__:




impute_method: directly

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.394484, total=   0.7s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.147422, total=   0.8s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.112713, total=   0.7s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.383875, total=   1.8s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.107836, total=   2.0s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.147082, total=   2.5s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.108792, total=   3.5s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.375465, total=   2.9s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.146583, total=   4.2s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.9s remaining:    3.0s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.8s remaining:    1.4s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.7s finished
INFO:__main__:It takes 246.51 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 1, model_id: d05c2abb-a2b5-45ec-b73d-9d4796cbc87c,model_name: random_forest, impute_method: directly, model_selector: hard_threshold_10, eval_metric: 56.00000000000001using 472.81 seconds
INFO:__main__:




impute_method: slinear

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.088512, total=   0.5s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.310264, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.127180, total=   0.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.322302, total=   1.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.089984, total=   1.7s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.128156, total=   2.0s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.323961, total=   2.5s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.085193, total=   2.8s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.128290, total=   3.4s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.7s remaining:    2.5s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.3s remaining:    1.1s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    3.9s finished
INFO:__main__:It takes 225.15 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1573: RuntimeWarning: overflow encountered in multiply
  tol = S.max(axis=-1, keepdims=True) * max(M.shape[-2:]) * finfo(S.dtype).eps
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1458: RuntimeWarning: overflow encountered in square
  eigvals = self._wexog_singular_values ** 2
/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:116: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 2, model_id: b62e5ca5-0c83-4e21-af61-4122ecda467c,model_name: random_forest, impute_method: slinear, model_selector: hard_threshold_10, eval_metric: 44.0using 433.94 seconds
INFO:__main__:




impute_method: cubic

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.394484, total=   0.5s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.112713, total=   0.7s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.147422, total=   0.7s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.383875, total=   1.5s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.107836, total=   1.9s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.147082, total=   2.3s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.375465, total=   2.7s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.108792, total=   3.2s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.146583, total=   3.9s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.8s remaining:    2.8s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.6s remaining:    1.3s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.4s finished
INFO:__main__:It takes 228.80 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 3, model_id: e93bf204-a8bf-47f1-8b6b-db097c4495b0,model_name: random_forest, impute_method: cubic, model_selector: hard_threshold_10, eval_metric: 56.00000000000001using 452.00 seconds
INFO:__main__:




impute_method: zero

INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_train: (1530, 11), y: (1530,)
Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.394484, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.112713, total=   0.6s
[CV] model__n_estimators=100 .........................................
[CV] ......... model__n_estimators=100, score=-0.147422, total=   0.7s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.383875, total=   1.6s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.107836, total=   1.9s
[CV] model__n_estimators=500 .........................................
[CV] ......... model__n_estimators=500, score=-0.147082, total=   2.3s
[CV] model__n_estimators=1000 ........................................
[CV] ........ model__n_estimators=1000, score=-0.375465, total=   2.9s
[Parallel(n_jobs=-1)]: Done   2 out of   9 | elapsed:    0.8s remaining:    2.7s
[Parallel(n_jobs=-1)]: Done   6 out of   9 | elapsed:    2.6s remaining:    1.3s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    4.3s finished
INFO:__main__:It takes 233.26 seconds to train this model.
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
/opt/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1574: RuntimeWarning: invalid value encountered in greater
  return (S > tol).sum(axis=-1)
/opt/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:1036: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/opt/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
INFO:__main__:X_test: (25, 11)
train_test_utils.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  X_copy['predict_y'] = y_predict
INFO:__main__:Model 4, model_id: 642a8324-585e-4434-82e1-dcbab3dfd55a,model_name: random_forest, impute_method: zero, model_selector: hard_threshold_10, eval_metric: 56.00000000000001using 455.23 seconds
INFO:__main__:We have run 5 models, using 1813.99 seconds
INFO:__main__:Saving d05c2abb-a2b5-45ec-b73d-9d4796cbc87c to disk...
INFO:__main__:Model dumped into ../results/models/model_d05c2abb-a2b5-45ec-b73d-9d4796cbc87c.pkl.
INFO:__main__:Saving e93bf204-a8bf-47f1-8b6b-db097c4495b0 to disk...
INFO:__main__:Model dumped into ../results/models/model_e93bf204-a8bf-47f1-8b6b-db097c4495b0.pkl.
INFO:__main__:By filtering the best eval_metric, we select the only model d05c2abb-a2b5-45ec-b73d-9d4796cbc87c, with eval_metric: 56.00000000000001
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
INFO:__main__:X_test: (5, 11)
INFO:__main__:Model: d05c2abb-a2b5-45ec-b73d-9d4796cbc87c, model_name: random_forest, metric: 56.00000000000001
INFO:feature_selecting.hard_thresholding:There are in total 628 columns, while we only need 10 columns
INFO:__main__:X_test: (5, 11)
INFO:__main__:Model: e93bf204-a8bf-47f1-8b6b-db097c4495b0, model_name: random_forest, metric: 56.00000000000001
INFO:__main__:Prediction finished!!!
done
